[Db]
    Dns = "host=127.0.0.1 user=writer password=123 dbname=xiaohuazhu port=5432 sslmode=disable TimeZone=Asia/Shanghai"
    PreferSimpleProtocol = true

[Oss]
    Endpoint = "127.0.0.1:9000"
    AccessPrefix = "http://127.0.0.1/"
    Id = "minio"
    Secret = "123456789"
    Token = ""
