[Db]
    Dns = "host=192.168.0.116 user=writer password=123 dbname=xiaohuazhu port=5432 sslmode=disable TimeZone=Asia/Shanghai"
    PreferSimpleProtocol = true

[Oss]
    Endpoint = "192.168.0.116:9000"
    Id = "minio"
    Secret = "123456789"
    Token = ""